name: Zip Dirs

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find changed dirs
        id: dirs
        run: |
          if git rev-parse --verify "${{ github.sha }}^" >/dev/null 2>&1; then
            CHANGED_DIRS=$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | cut -d/ -f1 | sort -u)
          else
            CHANGED_DIRS=$(git ls-tree --name-only -d HEAD)
          fi
          echo "dirs=$CHANGED_DIRS" >> $GITHUB_OUTPUT

      - name: Zip changed dirs
        if: steps.dirs.outputs.dirs != ''
        run: |
          mkdir -p zips
          for d in ${{ steps.dirs.outputs.dirs }}; do
            if [ -d "$d" ]; then
              zip -r "zips/${d}_${GITHUB_REF_NAME}_${GITHUB_SHA::7}.zip" "$d"
            fi
          done

      - name: Upload zips to release
        if: steps.dirs.outputs.dirs != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: branch-${{ github.ref_name }}
          name: "Branch ${{ github.ref_name }}"
          files: zips/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
